### ISSUE TITLE
No explanation of configurable variables included in the readme

### ISSUE THREAD

**Issue by mikeloeven** [Zoryn4163/SMAPI-Mods#10]
Would you kindly add a brief explanation of what the variables in the configuration files of your mods actually do for those of us who are not familiar with the games math?

**Comment by ghost** [comment]
@mikeloeven Because I had this same issue, and for any future users that are also confused, I went ahead and looked through the code in order to figure it out. 

Replace the 'X' with either 'Stamina' or 'Health', as it applies to both:

- _RegenXConstant_: whether to be constantly regenerating
- _RegenXConstantIsNegative_: dependent on _RegenXConstant_; whether the regeneration should take away, rather than give (I don't know why you would want this though)
- _RegenXConstantAmountPerSecond_: dependent on _RegenXConstant_; how much to regenerate per second
- _RegenXStill_: whether to regenerate while standing still
- _RegenXStillIsNegative_: dependent on _RegenXStill_; whether the regeneration should be negative
- _RegenXStillAmountPerSecond_: dependent on _RegenXStill_; how much to regenerate per second
- _RegenXStillTimeRequiredMS_: dependent on _RegenXStill_; the number of milliseconds you have to wait before it starts regenerating (note: 1000ms = 1 second)

To be more clear about the "dependencies": if you have the parent variable as 'false', no changes will be seen...e.g. if you have _RegenXConstantAmountPerSecond_ as 10, as long as _RegenXConstant_ is set to 'false', you won't regenerate anything.

Also important to note that both the 'constant' variables and the 'still' variables stack on top of each other. So if you have it regenerating a constant 1 health per second, and have it regenerate 5 health per second after standing for 1 second, then after that 1 second of standing still, you'll be regenerating 6 health per second.

On a final note to @Zoryn4163 ... Feel free to include any form of what I've written in the description. And it would be easier to understand if you removed the 'IsNegative' variables in place of just allowing the original values to be constant. It would also be nicer if you could have the option to have it slowly increase over time (with a cap).

**Comment by Pathoschild** [comment]
The readme for each mod now documents its config settings. :)
